FROM debian:bullseye-slim

# Install sqitch and postgres client
RUN apt-get update && apt-get install -y \
    sqitch \
    postgresql-client \
    libdbd-pg-perl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["sqitch", "deploy", "dev"]
